export enum ModalName{
    SUNBRELLA_MODAL = 'SUNBRELLA_MODAL',
    OXFORD_900_D = 'OXFORD_900_D',
    SEASTAR_ACRIL = 'SEASTAR_ACRIL'
}

export enum ActionsType {
    SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW',
    CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW',
    FETCH_MATERIAL_REQUEST = 'FETCH_MATERIAL_REQUEST',
    FETCH_MATERIAL_SUCCESS = 'FETCH_MATERIAL_SUCCESS',
    FETCH_MATERIAL_ERROR = 'FETCH_MATERIAL_ERROR',
    SELECT_MATERIAL = 'SELECT_MATERIAL'
}

